# https://github.com/katze225

commands:
  - 'money'
  - 'eco'
  - 'op'
  - 'deop'
  - 'gm'
  - 'gamemode'
  - 'give'
  - 'tp'
  - 'tphere'
  - 'tphere'
  - 'tpo'
  - 'tpo'
  - 'ban'
  - 'tempban'
  - 'unban'
  - 'unmute'
  - 'mute'
  - 'tempmute'
  - 'dupeip'
  - 'alts'
  - 'ipban'
  - 'ipmute'
  - '/set'
  - '/replace'
  - '/undo'
  - 'grim'